// カテゴリ一覧
const categories = [
    "New","ミライト復刻", "季節", "ネタ", "笑", "定番", "専用", "えらい", "挨拶", "ステージ", "LOVE"
];

// 仮のギフトデータ（カテゴリ追加）
const gifts = [
    
 // --- New ---
    { name: '5th Anniversary!!+', category: 'New', src: 'ギフト/New/5th Anniversary!+_1,000pt.jpg' },
    { name: '4th Anniversary!!+', category: 'New', src: 'ギフト/New/4th Anniversary!+_1,000pt.jpg' },
    { name: 'グー', category: 'New', src: 'ギフト/New/グー_5pt.jpg' },
    { name: 'チョキ', category: 'New', src: 'ギフト/New/チョキ_5pt.jpg' },
    { name: 'パー', category: 'New', src: 'ギフト/New/パー_5pt.jpg' },
    { name: 'オール', category: 'New', src: 'ギフト/New/オール_99pt.jpg' },
    { name: '3rd Anniversary!!+', category: 'New', src: 'ギフト/New/3rd Anniversary!+_1,000pt.jpg' },
    { name: 'セレブレーション', category: 'New', src: 'ギフト/New/セレブレーション_1,000pt.jpg' },

    // --- ミライト復刻 ---
    { name: '3rd Anniversary!!+', category: 'ミライト復刻', src: 'ギフト/New/3rd Anniversary!+_1,000pt.jpg' },
    { name: 'セレブレーション', category: 'ミライト復刻', src: 'ギフト/New/セレブレーション_1,000pt.jpg' },
    { name: '4th Anniversary!!+', category: 'ミライト復刻', src: 'ギフト/New/4th Anniversary!+_1,000pt.jpg' },
    { name: '5th Anniversary!!+', category: 'ミライト復刻', src: 'ギフト/New/5th Anniversary!+_1,000pt.jpg' },

    // --- 季節 ---
    { name: '秋色さぼぼん', category: '季節', src: 'ギフト/季節/秋色さぼぼん_5pt.jpg' },
    { name: '秋色しらす', category: '季節', src: 'ギフト/季節/秋色しらす_5pt.jpg' },
    { name: '秋色つむまる', category: '季節', src: 'ギフト/季節/秋色つむまる_5pt.jpg' },
    { name: '秋色ねこころ', category: '季節', src: 'ギフト/季節/秋色ねこころ_5pt.jpg' },
    { name: '秋色ぶくちゃ', category: '季節', src: 'ギフト/季節/秋色ぶくちゃ_5pt.jpg' },
    { name: '秋色ホシーカ', category: '季節', src: 'ギフト/季節/秋色ホシーカ_5pt.jpg' },
    { name: '秋色ユラミィ', category: '季節', src: 'ギフト/季節/秋色ユラミィ_5pt.jpg' },
    { name: 'Autumn Harmony', category: '季節', src: 'ギフト/季節/Autumn Harmony_100pt.jpg' },

    // ネタカテゴリ
    { name: 'もういっかい！', category: 'ネタ', src: 'ギフト/ネタ/もういっかい！_5pt.PNG' },
    { name: 'ダウト', category: 'ネタ', src: 'ギフト/ネタ/ダウト_5pt.PNG' },
    { name: 'ざわ…ざわ…', category: 'ネタ', src: 'ギフト/ネタ/ざわ…ざわ…_5pt.PNG' },
    { name: 'ファイヤー', category: 'ネタ', src: 'ギフト/ネタ/ファイヤー_5pt.PNG' },
    { name: '非常口', category: 'ネタ', src: 'ギフト/ネタ/非常口_5pt.PNG' },
    { name: 'いつもので', category: 'ネタ', src: 'ギフト/ネタ/いつもので_5pt.PNG' },
    { name: 'かー', category: 'ネタ', src: 'ギフト/ネタ/かー_5pt.PNG' },
    { name: 'つー', category: 'ネタ', src: 'ギフト/ネタ/つー_5pt.PNG' },
    { name: '一体感', category: 'ネタ', src: 'ギフト/ネタ/一体感_5pt.PNG' },
    { name: '乗りなッ！', category: 'ネタ', src: 'ギフト/ネタ/乗りなッ！_5pt.PNG' },
    { name: '降りろ…', category: 'ネタ', src: 'ギフト/ネタ/降りろ…_5pt.PNG' },
    { name: 'しーっ', category: 'ネタ', src: 'ギフト/ネタ/しーっ_5pt.PNG' },
    { name: 'はて…？', category: 'ネタ', src: 'ギフト/ネタ/はて…？_5pt.PNG' },
    { name: 'やれやれ', category: 'ネタ', src: 'ギフト/ネタ/やれやれ_5pt.PNG' },
    { name: 'ばぁ。', category: 'ネタ', src: 'ギフト/ネタ/ばぁ。_5pt.PNG' },
    { name: '完全燃焼', category: 'ネタ', src: 'ギフト/ネタ/完全燃焼_5pt.PNG' },
    { name: '激熱', category: 'ネタ', src: 'ギフト/ネタ/激熱_5pt.PNG' },
    { name: 'まぶしい', category: 'ネタ', src: 'ギフト/ネタ/まぶしい_5pt.PNG' },
    { name: '世界一', category: 'ネタ', src: 'ギフト/ネタ/世界一_5pt.PNG' },
    { name: '祭うちわ', category: 'ネタ', src: 'ギフト/ネタ/祭うちわ_5pt.PNG' },
    { name: 'ええやん', category: 'ネタ', src: 'ギフト/ネタ/ええやん_5pt.PNG' },
    { name: '最強', category: 'ネタ', src: 'ギフト/ネタ/最強_5pt.PNG' },
    { name: 'スリスリ', category: 'ネタ', src: 'ギフト/ネタ/スリスリ_5pt.PNG' },
    { name: '中二病', category: 'ネタ', src: 'ギフト/ネタ/中二病_5pt.PNG' },
    { name: '拳', category: 'ネタ', src: 'ギフト/ネタ/拳_5pt.PNG' },
    { name: 'ふぅー！！', category: 'ネタ', src: 'ギフト/ネタ/ふぅー！！_5pt.PNG' },
    { name: 'メシウマ', category: 'ネタ', src: 'ギフト/ネタ/メシウマ_5pt.PNG' },
    { name: 'アニキー！', category: 'ネタ', src: 'ギフト/ネタ/アニキー！_5pt.PNG' },
    { name: '仰せのままに', category: 'ネタ', src: 'ギフト/ネタ/仰せのままに_5pt.PNG' },
    { name: '漢', category: 'ネタ', src: 'ギフト/ネタ/漢_5pt.PNG' },
    { name: '鉄アレイ', category: 'ネタ', src: 'ギフト/ネタ/鉄アレイ_5pt.PNG' },
    { name: 'しおしお…', category: 'ネタ', src: 'ギフト/ネタ/しおしお…_5pt.PNG' },
    { name: 'ヒャッホー！', category: 'ネタ', src: 'ギフト/ネタ/ヒャッホー！_5pt.PNG' },
    { name: 'あざとい', category: 'ネタ', src: 'ギフト/ネタ/あざとい_5pt.PNG' },
    { name: 'おもしれーやつ', category: 'ネタ', src: 'ギフト/ネタ/おもしれーやつ_5pt.PNG' },
    { name: '沼', category: 'ネタ', src: 'ギフト/ネタ/沼_5pt.PNG' },
    { name: '鳥肌注意', category: 'ネタ', src: 'ギフト/ネタ/鳥肌注意_5pt.PNG' },
    { name: 'スヤァ…', category: 'ネタ', src: 'ギフト/ネタ/スヤァ…_5pt.PNG' },
    { name: 'やりおる', category: 'ネタ', src: 'ギフト/ネタ/やりおる_5pt.PNG' },
    { name: 'あとは頼んだ', category: 'ネタ', src: 'ギフト/ネタ/あとは頼んだ_5pt.PNG' },
    { name: 'おねぎします。', category: 'ネタ', src: 'ギフト/ネタ/おねぎします。_5pt.PNG' },
    { name: 'まかセロリ', category: 'ネタ', src: 'ギフト/ネタ/まかセロリ_5pt.PNG' },
    { name: 'ドヤッ', category: 'ネタ', src: 'ギフト/ネタ/ドヤッ_5pt.PNG' },
    { name: 'ぱぁ', category: 'ネタ', src: 'ギフト/ネタ/ぱぁ_5pt.PNG' },
    { name: 'チャージ！', category: 'ネタ', src: 'ギフト/ネタ/チャージ！_100pt.PNG' },
    { name: 'ひんやり', category: 'ネタ', src: 'ギフト/ネタ/ひんやり_5pt.PNG' },
    { name: 'アヂッ', category: 'ネタ', src: 'ギフト/ネタ/アヂッ_5pt.PNG' },
    { name: 'つむっ！！', category: 'ネタ', src: 'ギフト/ネタ/つむっ！！_5pt.PNG' },
    { name: 'おばけしらす', category: 'ネタ', src: 'ギフト/ネタ/おばけしらす_44pt.PNG' },
    { name: 'オール', category: 'ネタ', src: 'ギフト/ネタ/オール_5pt.PNG' },
    { name: 'しらすまん', category: 'ネタ', src: 'ギフト/ネタ/しらすまん_5pt.PNG' },
    { name: 'ダウト(200pt)', category: 'ネタ', src: 'ギフト/ネタ/ダウト(200pt).jpg' },
    { name: '爆弾', category: 'ネタ', src: 'ギフト/ネタ/爆弾_5pt.PNG' },
    { name: 'カチコチ', category: 'ネタ', src: 'ギフト/ネタ/カチコチ_5pt.PNG' },
    { name: '蝋燭', category: 'ネタ', src: 'ギフト/ネタ/蝋燭_5pt.PNG' },
    { name: 'どーなつちゃうの？', category: 'ネタ', src: 'ギフト/ネタ/どーなつちゃうの？_5pt.PNG' },
    { name: '嫁に来ないか', category: 'ネタ', src: 'ギフト/ネタ/嫁に来ないか_500pt.PNG' },
    { name: 'そういうとこだぞ', category: 'ネタ', src: 'ギフト/ネタ/そういうとこだぞ_5pt.PNG' },
    { name: 'ん・・・？', category: 'ネタ', src: 'ギフト/ネタ/ん・・・？_5pt.PNG' },
    { name: 'パシャパシャ', category: 'ネタ', src: 'ギフト/ネタ/パシャパシャ_5pt.PNG' },
    { name: '集中線', category: 'ネタ', src: 'ギフト/ネタ/集中線_5pt.PNG' },
    { name: '警察だ！', category: 'ネタ', src: 'ギフト/ネタ/警察だ！_5pt.PNG' },
    { name: 'パイ投げ', category: 'ネタ', src: 'ギフト/ネタ/パイ投げ_5pt.PNG' },
    { name: 'タライ落とし', category: 'ネタ', src: 'ギフト/ネタ/タライ落とし_5pt.PNG' },
    { name: 'しらすレインボー', category: 'ネタ', src: 'ギフト/ネタ/しらすレインボー_5pt.PNG' },
    { name: 'ギガフルーム', category: 'ネタ', src: 'ギフト/ネタ/ギガフルーム_5pt.PNG' },
    { name: 'まだ大丈夫。。', category: 'ネタ', src: 'ギフト/ネタ/まだ大丈夫。。_5pt.PNG' },
    { name: '気配感知', category: 'ネタ', src: 'ギフト/ネタ/気配感知_5pt.PNG' },
    { name: 'REC', category: 'ネタ', src: 'ギフト/ネタ/REC_5pt.PNG' },
    { name: 'お宝発見', category: 'ネタ', src: 'ギフト/ネタ/お宝発見_1,000pt.PNG' },
    { name: 'あちらのお客様からです', category: 'ネタ', src: 'ギフト/ネタ/あちらのお客様からです_3,000pt.PNG' },

    { name: 'www', category: '笑', src: 'ギフト/笑/www_5pt.png' },
    { name: '草', category: '笑', src: 'ギフト/笑/草_5pt.png' },
    { name: 'ドッ', category: '笑', src: 'ギフト/笑/ドッ_5pt.png' },
    { name: 'かぷかぷ', category: '笑', src: 'ギフト/笑/かぷかぷ_5pt.png' },
    { name: 'こらえ笑い', category: '笑', src: 'ギフト/笑/こらえ笑い_5pt.png' },
    { name: 'ブフォッ', category: '笑', src: 'ギフト/笑/ブフォッ_5pt.png' },
    { name: '微笑', category: '笑', src: 'ギフト/笑/微笑_5pt.png' },
    { name: '真顔', category: '笑', src: 'ギフト/笑/真顔_5pt.png' },
    { name: '草(植物)', category: '笑', src: 'ギフト/笑/草(植物)_5pt.png' },
    { name: 'おもしれー', category: '笑', src: 'ギフト/笑/おもしれー_5pt.png' },
    { name: 'ガハハ', category: '笑', src: 'ギフト/笑/ガハハ_5pt.png' },
    { name: 'ズコー', category: '笑', src: 'ギフト/笑/ズコー_5pt.png' },
    { name: '座布団', category: '笑', src: 'ギフト/笑/座布団_5pt.png' },
    { name: 'ビタミン不足', category: '笑', src: 'ギフト/笑/ビタミン不足_5pt.png' },
    { name: 'ウケる', category: '笑', src: 'ギフト/笑/ウケる_5pt.png' },
    { name: '草(大)', category: '笑', src: 'ギフト/笑/草(大)_100pt.png' },

    // 定番カテゴリ
    { name: 'うんうん', icon: '', category: '定番' ,src: 'ギフト/定番/うんうん_5pt.png' },
    { name: 'なるほど', icon: '', category: '定番' ,src: 'ギフト/定番/なるほど_5pt.png' },
    { name: 'わかる', icon: '', category: '定番' ,src: 'ギフト/定番/わかる_5pt.png' },
    { name: 'わからん', icon: '', category: '定番' ,src: 'ギフト/定番/わからん_5pt.png' },
    { name: '爆笑', icon: '', category: '定番' ,src: 'ギフト/定番/爆笑_5pt.png' },
    { name: '号泣', icon: '', category: '定番' ,src: 'ギフト/定番/号泣_5pt.png' },
    { name: '考え中', icon: '', category: '定番' ,src: 'ギフト/定番/考え中_5pt.png' },
    { name: '好物', icon: '', category: '定番' ,src: 'ギフト/定番/好物_5pt.png' },
    { name: 'ふ～ん', icon: '', category: '定番' ,src: 'ギフト/定番/ふ～ん_5pt.png' },
    { name: '・・・', icon: '', category: '定番' ,src: 'ギフト/定番/・・・_5pt.png' },
    { name: '？', icon: '', category: '定番' ,src: 'ギフト/定番/？_5pt.png' },
    { name: '！？', icon: '', category: '定番' ,src: 'ギフト/定番/！？_5pt.png' },
    { name: 'ありがとう！', icon: '', category: '定番' ,src: 'ギフト/定番/ありがとう！_5pt.png' },
    { name: 'やだ', icon: '', category: '定番' ,src: 'ギフト/定番/やだ_5pt.png' },
    { name: 'ダウト', icon: '', category: '定番' ,src: 'ギフト/定番/ダウト_5pt.png' },
    { name: 'www', icon: '', category: '定番' ,src: 'ギフト/定番/www_5pt.png' },
    { name: '草', icon: '', category: '定番' ,src: 'ギフト/定番/草_5pt.png' },
    { name: '神', icon: '', category: '定番' ,src: 'ギフト/定番/神_5pt.png' },
    { name: 'キャンディ', icon: '', category: '定番' ,src: 'ギフト/定番/キャンディ_5pt.png' },
    { name: '炎', icon: '', category: '定番' ,src: 'ギフト/定番/炎_5pt.png' },
    { name: '握手', icon: '', category: '定番' ,src: 'ギフト/定番/握手_5pt.png' },
    { name: 'ハイ！', icon: '', category: '定番' ,src: 'ギフト/定番/ハイ！_5pt.png' },
    { name: '助かる', icon: '', category: '定番' ,src: 'ギフト/定番/助かる_5pt.png' },
    { name: 'クラッカー', icon: '', category: '定番' ,src: 'ギフト/定番/クラッカー_5pt.png'  },
    { name: '良さそう', icon: '', category: '定番' ,src: 'ギフト/定番/良さそう_5pt.png'  },
    { name: 'クローバー', icon: '', category: '定番' ,src: 'ギフト/定番/クローバー_5pt.png'  },
    { name: 'ドリンク', icon: '', category: '定番' ,src: 'ギフト/定番/ドリンク_5pt.png'  },
    { name: 'ぴえん', icon: '', category: '定番' ,src: 'ギフト/定番/ぴえん_5pt.png'  },
    { name: 'バラ', icon: '', category: '定番' ,src: 'ギフト/定番/バラ_5pt.png'  },
    { name: 'いつもので', icon: '', category: '定番' ,src: 'ギフト/定番/いつもので_5pt.png'  },
    { name: '一体感', icon: '', category: '定番' ,src: 'ギフト/定番/一体感_5pt.png'  },
    { name: 'ドッ', icon: '', category: '定番' ,src: 'ギフト/定番/ドッ_5pt.png'  },
    { name: 'ごはん', icon: '', category: '定番', src: 'ギフト/定番/ごはん_5pt.png'  },
    { name: 'サラダバー', icon: '', category: '定番', src: 'ギフト/定番/サラダバー_5pt.png'  },
    { name: '草(植物)', icon: '', category: '定番', src: 'ギフト/定番/草(植物)_5pt.png'  },
    { name: 'えへへ', icon: '', category: '定番',  src: 'ギフト/定番/えへへ_5pt.png'  },
    { name: 'うぐぅ・・・', icon: '', category: '定番',  src: 'ギフト/定番/うぐぅ・・・_5pt.png'  },
    { name: 'ガクブル', icon: '', category: '定番' ,  src: 'ギフト/定番/ガクブル_5pt.png'  },
    { name: 'サァーー', icon: '', category: '定番' ,  src: 'ギフト/定番/サァーー_5pt.png'  },
    { name: 'ナムナム', icon: '', category: '定番' , src: 'ギフト/定番/ナムナム_5pt.png'  },
    { name: 'ヒェッ', icon: '', category: '定番',  src: 'ギフト/定番/ヒェッ_5pt.png'  },
    { name: 'ちょっと', icon: '', category: '定番', src: 'ギフト/定番/ちょっと_5pt.png'  },
    { name: 'むっちゃ', icon: '', category: '定番', src: 'ギフト/定番/むっちゃ_5pt.png'  },
    { name: 'もっと', icon: '', category: '定番', src: 'ギフト/定番/もっと_5pt.png'  },
    { name: 'エナジードリンク', icon: '', category: '定番', src: 'ギフト/定番/エナジードリンク_5pt.png'  },
    { name: '拍手', icon: '', category: '定番', src: 'ギフト/定番/拍手_5pt.png'  },
    { name: 'ふぅー！！', icon: '', category: '定番', src: 'ギフト/定番/ふぅー！！_5pt.png'  },
    { name: 'おいしいやつ！', icon: '', category: '定番',   src: 'ギフト/定番/おいしいやつ！_5pt.png'  },
    { name: 'おかわり！', icon: '', category: '定番',   src: 'ギフト/定番/おかわり！_5pt.png'  },
    { name: 'おなかいっぱい', icon: '', category: '定番' ,   src: 'ギフト/定番/おなかいっぱい_5pt.png'  },
    { name: 'おなかすいた', icon: '', category: '定番' ,   src: 'ギフト/定番/おなかすいた_5pt.png'  },
    { name: 'ごっつぁんです', icon: '', category: '定番',   src: 'ギフト/定番/ごっつぁんです_5pt.png'  },
    { name: 'じゅるり', icon: '', category: '定番' ,  src: 'ギフト/定番/じゅるり_5pt.png'  },
    { name: 'オサレ', icon: '', category: '定番',  src: 'ギフト/定番/オサレ_5pt.png'  },
    { name: 'いえーい！', icon: '', category: '定番',  src: 'ギフト/定番/いえーい！_5pt.png'  },
    { name: 'うむうむ', icon: '', category: '定番',  src: 'ギフト/定番/うむうむ_5pt.png'  },
    { name: 'きゅるん', icon: '', category: '定番',  src: 'ギフト/定番/きゅるん_5pt.png'  },
    { name: 'ごろごろ', icon: '', category: '定番',  src: 'ギフト/定番/ごろごろ_5pt.png'  },
    { name: 'ぺこぺこ', icon: '', category: '定番',  src: 'ギフト/定番/ぺこぺこ_5pt.png'  },
    { name: 'あわわわ', icon: '', category: '定番',  src: 'ギフト/定番/あわわわ_5pt.png'  },
    { name: 'しおしお', icon: '', category: '定番' , src: 'ギフト/定番/しおしお_5pt.png'  },
    { name: 'ぽかぽか', icon: '', category: '定番',  src: 'ギフト/定番/ぽかぽか_5pt.png'  },
    { name: 'やば～い', icon: '', category: '定番', src: 'ギフト/定番/やば～い_5pt.png'  },
    { name: 'ウケる', icon: '', category: '定番', src: 'ギフト/定番/ウケる_5pt.png'  },
    { name: 'ビクッ！？', icon: '', category: '定番', src: 'ギフト/定番/ビクッ！？_5pt.png'  },
    { name: 'ファイティン', icon: '', category: '定番', src: 'ギフト/定番/ファイティン_5pt.png'  },
    { name: '？？？', icon: '', category: '定番', src: 'ギフト/定番/？？？_5pt.png'  },
    { name: 'はぁい・・・', icon: '', category: '定番', src: 'ギフト/定番/はぁい・・・_5pt.png'  },
    { name: 'ふんふん・・・', icon: '', category: '定番', src: 'ギフト/定番/ふんふん・・・_5pt.png'  },
    { name: 'おねが～い', icon: '', category: '定番', src: 'ギフト/定番/おねが～い_5pt.png'  },
    { name: 'ぱぁぁ', icon: '', category: '定番', src: 'ギフト/定番/ぱぁぁ_5pt.png'  },
    { name: 'ぷんぷん', icon: '', category: '定番', src: 'ギフト/定番/ぷんぷん_5pt.png'  },
    { name: 'ふぉっふぉっ', icon: '', category: '定番', src: 'ギフト/定番/ふぉっふぉっ_5pt.png'  },
    { name: 'メンタルブレイク', icon: '', category: '定番', src: 'ギフト/定番/メンタルブレイク_5pt.png'  },
    { name: 'いっくよー！', icon: '', category: '定番', src: 'ギフト/定番/いっくよー！_5pt.png'  },
    { name: 'おねぎします。', icon: '', category: '定番', src: 'ギフト/定番/おねぎします。_5pt.png'  },
    { name: 'まかセロリ', icon: '', category: '定番', src: 'ギフト/定番/まかセロリ_5pt.png'  },
    { name: 'ぱぁ', icon: '', category: '定番', src: 'ギフト/定番/ぱぁ_5pt.png'  },
    { name: 'ぱぁぁぁ', icon: '', category: '定番', src: 'ギフト/定番/ぱぁぁぁ_5pt.png'  },
    { name: 'ひそひそ', icon: '', category: '定番', src: 'ギフト/定番/ひそひそ_5pt.png'  },
    { name: 'ポカーン', icon: '', category: '定番', src: 'ギフト/定番/ポカーン_5pt.png'  },
    { name: '閃き', icon: '', category: '定番', src: 'ギフト/定番/閃き_5pt.png'  },
    { name: 'のど飴', icon: '', category: '定番', src: 'ギフト/定番/のど飴_5pt.png'  },
    { name: '休んで！', icon: '', category: '定番', src: 'ギフト/定番/休んで！_5pt.png'  },
    { name: '寝て！', icon: '', category: '定番', src: 'ギフト/定番/寝て！_5pt.png'  },
    { name: '食べて！', icon: '', category: '定番', src: 'ギフト/定番/食べて！_5pt.png'  },
    { name: '充電中', icon: '', category: '定番', src: 'ギフト/定番/充電中_5pt.png'  },
    { name: '残量100%', icon: '', category: '定番', src: 'ギフト/定番/残量100%_5pt.png'  },
    { name: '残量1%', icon: '', category: '定番', src: 'ギフト/定番/残量1%_5pt.png'  },
    { name: 'グー', icon: '', category: '定番', src: 'ギフト/定番/グー_5pt.png'  },
    { name: 'チョキ', icon: '', category: '定番', src: 'ギフト/定番/チョキ_5pt.png'  },
    { name: 'パー', icon: '', category: '定番', src: 'ギフト/定番/パー_5pt.png'  },
    { name: 'シャキーン', icon: '', category: '定番', src: 'ギフト/定番/シャキーン_5pt.png'  },
    { name: 'キラキラ', icon: '', category: '定番', src: 'ギフト/定番/キラキラ_5pt.png'  },
    { name: 'ひんやりタイム', icon: '', category: '定番', src: 'ギフト/定番/ひんやりタイム_5pt.png'  },
    { name: '・・・どれ？', icon: '', category: '定番', src: 'ギフト/定番/・・・どれ？_5pt.png'  },
    { name: '一本締め', icon: '', category: '定番', src: 'ギフト/定番/一本締め_5pt.png'  },
    { name: '草(大)', icon: '', category: '定番', src: 'ギフト/定番/草(大)_100pt.png'  },
    { name: 'お茶', icon: '', category: '定番', src: 'ギフト/定番/お茶_100pt.png'  },
    { name: 'えらい', icon: '', category: '定番', src: 'ギフト/定番/えらい_100pt.png'  },
    { name: 'クラッカー(大)', icon: '', category: '定番', src: 'ギフト/定番/クラッカー(大)_100pt.png'  },
    { name: 'バラ(大)', icon: '', category: '定番', src: 'ギフト/定番/バラ(大)_100pt.png'  },
    { name: '御意', icon: '', category: '定番', src: 'ギフト/定番/御意_100pt.png'  },
    { name: 'しらすまん', icon: '', category: '定番', src: 'ギフト/定番/しらすまん_200pt.png'  },
    { name: 'ダウト(大)', icon: '', category: '定番', src: 'ギフト/定番/ダウト(大)_200pt.png'  },
    { name: '怒り', icon: '', category: '定番', src: 'ギフト/定番/怒り_200pt.png'  },
    { name: '頑張れ', icon: '', category: '定番', src: 'ギフト/定番/頑張れ_200pt.png'  },
    { name: '乾杯', icon: '', category: '定番', src: 'ギフト/定番/乾杯_200pt.png'  },
    { name: 'エモい', icon: '', category: '定番', src: 'ギフト/定番/エモい_5pt.png'  },
    { name: '花束', icon: '', category: '定番', src: 'ギフト/定番/花束_500pt.png'  },
    { name: 'ありがとう！(大)', icon: '', category: '定番', src: 'ギフト/定番/ありがとう！(大)_500pt.png'  },
    { name: '助かる(大)', icon: '', category: '定番', src: 'ギフト/定番/助かる(大)_500pt.png'  },
    { name: 'ん・・・？', icon: '', category: '定番', src: 'ギフト/定番/ん・・・？_500pt.png'  },
    { name: 'うわぁぁん', icon: '', category: '定番', src: 'ギフト/定番/うわぁぁん_500pt.png'  },
    { name: 'ウィンクチャレンジ', icon: '', category: '定番', src: 'ギフト/定番/ウィンクチャレンジ_500pt.png'  },
    { name: 'フレーム猫耳', icon: '', category: '定番', src: 'ギフト/定番/フレーム猫耳_500pt.png'  },
    { name: 'タピオカ', icon: '', category: '定番', src: 'ギフト/定番/タピオカ_500pt.png'  },
    { name: 'くす玉', icon: '', category: '定番', src: 'ギフト/定番/くす玉_700pt.png'  },
    { name: '缶詰(風船)', icon: '', category: '定番', src: 'ギフト/定番/缶詰(風船)_1,000pt.png'  },
    { name: 'イリアム特性パフェ', icon: '', category: '定番', src: 'ギフト/定番/イリアム特性パフェ_1,500pt.png'  },
    { name: '缶詰(花)', icon: '', category: '定番', src: 'ギフト/定番/缶詰(花)_2,000pt.png'  },
    { name: '缶詰タワー', icon: '', category: '定番', src: 'ギフト/定番/缶詰タワー_3,000pt.png'  },

    // 専用カテゴリ
    { name: 'わいわい投票', icon: '', category: '専用', src: 'ギフト/専用/わいわい投票_500pt.png' },

    // えらいカテゴリ
    { name: 'キリおめ', icon: '', category: 'えらい', src: 'ギフト/えらい/キリおめ_5pt.PNG' },
    { name: 'ナイギフ', icon: '', category: 'えらい', src: 'ギフト/えらい/ナイギフ_5pt.PNG' },
    { name: 'ナイス', icon: '', category: 'えらい', src: 'ギフト/えらい/ナイス_5pt.PNG' },
    { name: 'かわいい', icon: '', category: 'えらい', src: 'ギフト/えらい/かわいい_5pt.png' },
    { name: '神', icon: '', category: 'えらい', src: 'ギフト/えらい/神_5pt.png' },
    { name: '100点', icon: '', category: 'えらい', src: 'ギフト/えらい/100点_5pt.png' },
    { name: '良さそう', icon: '', category: 'えらい', src: 'ギフト/えらい/良さそう_5pt.png' },
    { name: '世界一', icon: '', category: 'えらい', src: 'ギフト/えらい/世界一_5pt.png' },
    { name: 'えぐぐ', icon: '', category: 'えらい', src: 'ギフト/えらい/えぐぐ_5pt.png' },
    { name: 'すごい', icon: '', category: 'えらい', src: 'ギフト/えらい/すごい_5pt.png' },
    { name: 'すばら', icon: '', category: 'えらい', src: 'ギフト/えらい/すばら_5pt.png' },
    { name: 'たのしみ', icon: '', category: 'えらい', src: 'ギフト/えらい/たのしみ_5pt.png' },
    { name: 'ええやん', icon: '', category: 'えらい', src: 'ギフト/えらい/ええやん_5pt.png' },
    { name: '天才か！？', icon: '', category: 'えらい', src: 'ギフト/えらい/天才か！？_5pt.png' },
    { name: '最強', icon: '', category: 'えらい', src: 'ギフト/えらい/最強_5pt.png' },
    { name: 'かしこ', icon: '', category: 'えらい', src: 'ギフト/えらい/かしこ_5pt.png' },
    { name: 'はなまる', icon: '', category: 'えらい', src: 'ギフト/えらい/はなまる_5pt.png' },
    { name: '拍手', icon: '', category: 'えらい', src: 'ギフト/えらい/拍手_5pt.png' },
    { name: 'エモい', icon: '', category: 'えらい', src: 'ギフト/えらい/エモい_5pt.png' },
    { name: 'チルい', icon: '', category: 'えらい', src: 'ギフト/えらい/チルい_5pt.png' },
    { name: 'かっこいい', icon: '', category: 'えらい', src: 'ギフト/えらい/かっこいい_5pt.png' },
    { name: 'イケボ', icon: '', category: 'えらい', src: 'ギフト/えらい/イケボ_5pt.png' },
    { name: 'オサレ', icon: '', category: 'えらい', src: 'ギフト/えらい/オサレ_5pt.png' },
    { name: 'クール', icon: '', category: 'えらい', src: 'ギフト/えらい/クール_5pt.png' },
    { name: 'アニキー！', icon: '', category: 'えらい', src: 'ギフト/えらい/アニキー！_5pt.png' },
    { name: '漢', icon: '', category: 'えらい', src: 'ギフト/えらい/漢_5pt.png' },
    { name: 'あざとい', icon: '', category: 'えらい', src: 'ギフト/えらい/あざとい_5pt.png' },
    { name: 'おもしれーやつ', icon: '', category: 'えらい', src: 'ギフト/えらい/おもしれーやつ_5pt.png' },
    { name: 'かわぼ', icon: '', category: 'えらい', src: 'ギフト/えらい/かわぼ_5pt.png' },
    { name: '癒やし～', icon: '', category: 'えらい', src: 'ギフト/えらい/癒やし～_5pt.png' },
    { name: '耳が幸せ', icon: '', category: 'えらい', src: 'ギフト/えらい/耳が幸せ_5pt.png' },
    { name: 'やりおる', icon: '', category: 'えらい', src: 'ギフト/えらい/やりおる_5pt.png' },
    { name: 'よかろう', icon: '', category: 'えらい', src: 'ギフト/えらい/よかろう_5pt.png' },
    { name: 'えらい', icon: '', category: 'えらい', src: 'ギフト/えらい/えらい_100pt.png' },
    { name: 'Congratulations!', icon: '', category: 'えらい', src: 'ギフト/えらい/Congratulations!_100pt.png' },
    { name: 'クラッカー(大)', icon: '', category: 'えらい', src: 'ギフト/えらい/クラッカー(大)_200pt.png' },
    { name: '拍手(大)', icon: '', category: 'えらい', src: 'ギフト/えらい/拍手(大)_200pt.png' },
    { name: 'エモい(大)', icon: '', category: 'えらい', src: 'ギフト/えらい/エモい(大)_200pt.png' },
    { name: 'たいへんよくできました', icon: '', category: 'えらい', src: 'ギフト/えらい/たいへんよくできました_500pt.png' },
    { name: 'お見事', icon: '', category: 'えらい', src: 'ギフト/えらい/お見事_500pt.png' },
    { name: 'くす玉', icon: '', category: 'えらい', src: 'ギフト/えらい/くす玉_1,000pt.png' },
    { name: 'ケーキ(誕生日)', icon: '', category: 'えらい', src: 'ギフト/えらい/ケーキ(誕生日)_1,000pt.png' },
    { name: 'かわいい！', icon: '', category: 'えらい', src: 'ギフト/えらい/かわいい！_1,000pt.png' },
    { name: '尊い', icon: '', category: 'えらい', src: 'ギフト/えらい/尊い_5,000pt.png' },
    { name: 'なでなで', icon: '', category: 'えらい', src: 'ギフト/えらい/なでなで_7,000pt.png' },
    { name: 'ハッピーバースデー', icon: '', category: 'えらい', src: 'ギフト/えらい/ハッピーバースデー_10,000pt.png' },

    // 挨拶カテゴリ
    { name: 'はろー！', icon: '', category: '挨拶', src: 'ギフト/挨拶/はろー！_5pt.png' },
    { name: 'ようこそ', icon: '', category: '挨拶', src: 'ギフト/挨拶/ようこそ_5pt.png' },
    { name: 'おつかれさま', icon: '', category: '挨拶', src: 'ギフト/挨拶/おつかれさま_5pt.png' },
    { name: 'おはよう', icon: '', category: '挨拶', src: 'ギフト/挨拶/おはよう_5pt.png' },
    { name: 'こんばんは', icon: '', category: '挨拶', src: 'ギフト/挨拶/こんばんは_5pt.png' },
    { name: 'バイバイ', icon: '', category: '挨拶', src: 'ギフト/挨拶/バイバイ_5pt.png' },
    { name: '握手', icon: '', category: '挨拶', src: 'ギフト/挨拶/握手_5pt.png' },
    { name: 'おかえり', icon: '', category: '挨拶', src: 'ギフト/挨拶/おかえり_5pt.png' },
    { name: 'おやすみ', icon: '', category: '挨拶', src: 'ギフト/挨拶/おやすみ_5pt.png' },
    { name: 'いってきます', icon: '', category: '挨拶', src: 'ギフト/挨拶/いってきます_5pt.png' },  
    { name: 'いってらっしゃい', icon: '', category: '挨拶', src: 'ギフト/挨拶/いってらっしゃい_5pt.png' },
    { name: 'いらっしゃい', icon: '', category: '挨拶', src: 'ギフト/挨拶/いらっしゃい_5pt.png' },
    { name: 'おじゃまします', icon: '', category: '挨拶', src: 'ギフト/挨拶/おじゃまします_5pt.png' },
    { name: 'ただいま', icon: '', category: '挨拶', src: 'ギフト/挨拶/ただいま_5pt.png' },
    { name: 'やってる？', icon: '', category: '挨拶', src: 'ギフト/挨拶/やってる？_5pt.png' },
    { name: 'らっしゃっせい！', icon: '', category: '挨拶', src: 'ギフト/挨拶/らっしゃっせい！_5pt.png' }, 
    { name: '初見さんヤッホー', icon: '', category: '挨拶', src: 'ギフト/挨拶/初見さんヤッホー_5pt.png' },
    { name: '遅れた！！', icon: '', category: '挨拶', src: 'ギフト/挨拶/遅れた！！_5pt.png' },
    { name: 'すぐ戻る！', icon: '', category: '挨拶', src: 'ギフト/挨拶/すぐ戻る！_5pt.png' },   
    { name: 'トイレ', icon: '', category: '挨拶', src: 'ギフト/挨拶/トイレ_5pt.png' },
    { name: 'フロリダ', icon: '', category: '挨拶', src: 'ギフト/挨拶/フロリダ_5pt.png' },
    { name: 'しごもど', icon: '', category: '挨拶', src: 'ギフト/挨拶/しごもど_5pt.png' },
    { name: 'ちょい落ち', icon: '', category: '挨拶', src: 'ギフト/挨拶/ちょい落ち_5pt.png' },
    { name: 'サラダバー', icon: '', category: '挨拶', src: 'ギフト/挨拶/サラダバー_5pt.png' },
    { name: 'スッ', icon: '', category: '挨拶', src: 'ギフト/挨拶/スッ_5pt.png' },
    { name: 'ヤッホー', icon: '', category: '挨拶', src: 'ギフト/挨拶/ヤッホー_5pt.png' },
    { name: 'すやぁ・・・', icon: '', category: '挨拶', src: 'ギフト/挨拶/すやぁ・・・_5pt.png' },
    { name: 'やりおる', icon: '', category: '挨拶', src: 'ギフト/挨拶/やりおる_5pt.png' },
    { name: 'あとは頼んだ', icon: '', category: '挨拶', src: 'ギフト/挨拶/あとは頼んだ_5pt.png' },
    { name: 'おねぎします。', icon: '', category: '挨拶', src: 'ギフト/挨拶/おねぎします。_5pt.png' },
    { name: 'またね', icon: '', category: '挨拶', src: 'ギフト/挨拶/またね_5pt.png' },
    { name: '参上', icon: '', category: '挨拶', src: 'ギフト/挨拶/参上_5pt.png' },
    { name: 'こんにちは', icon: '', category: '挨拶', src: 'ギフト/挨拶/こんにちは_5pt.png' },
    { name: 'また来るね！', icon: '', category: '挨拶', src: 'ギフト/挨拶/また来るね！_5pt.png' },
    { name: 'おやすみ(大)', icon: '', category: '挨拶', src: 'ギフト/挨拶/おやすみ(大)_100pt.png' },

    // ステージカテゴリ
    {name: 'クラッカー', icon: '', category: 'ステージ',src: 'ギフト/ステージ/クラッカー_5pt.png'  },
    {name: 'サイリウム・オレンジ', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・オレンジ_5pt.png'  },
    {name: 'サイリウム・ピンク', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・ピンク_5pt.png'  },
    {name: 'サイリウム・白', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・白_5pt.png'  },
    {name: 'サイリウム・紫', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・紫_5pt.png'  },
    {name: 'サイリウム・緑', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・緑_5pt.png'  },
    {name: 'サイリウム・赤', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・赤_5pt.png'  },
    {name: 'サイリウム・青', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・青_5pt.png'  },
    {name: 'サイリウム・黄', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・黄_5pt.png'  },
    {name: 'サイリウム・黄緑', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・黄緑_5pt.png'  },
    {name: 'サイリウム・黒', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・黒_5pt.png'  },
    {name: 'いつもので', icon: '', category: 'ステージ',src: 'ギフト/ステージ/いつもので_5pt.png'  },
    {name: 'もっと', icon: '', category: 'ステージ',src: 'ギフト/ステージ/もっと_5pt.png'  },
    {name: '祭うちわ', icon: '', category: 'ステージ',src: 'ギフト/ステージ/祭うちわ_5pt.png'  },
    {name: '拍手', icon: '', category: 'ステージ',src: 'ギフト/ステージ/拍手_5pt.png'  },
    {name: 'サイリウム・葱', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サイリウム・葱_5pt.png'  },
    {name: '中二病', icon: '', category: 'ステージ',src: 'ギフト/ステージ/中二病_5pt.png'  },
    {name: 'アフロしらす', icon: '', category: 'ステージ',src: 'ギフト/ステージ/アフロしらす_5pt.png'  },
    {name: 'アンコール', icon: '', category: 'ステージ',src: 'ギフト/ステージ/アンコール_5pt.png'  }, 
    {name: 'ヘドバン', icon: '', category: 'ステージ',src: 'ギフト/ステージ/ヘドバン_5pt.png'  },
    {name: 'ふぅー！！', icon: '', category: 'ステージ',src: 'ギフト/ステージ/ふぅー！！_5pt.png'  },
    {name: 'キャーッ！', icon: '', category: 'ステージ',src: 'ギフト/ステージ/キャーッ！_5pt.png'  }, 
    {name: '音符', icon: '', category: 'ステージ',src: 'ギフト/ステージ/音符_100pt.png'  },
    {name: 'クラッカー(大)', icon: '', category: 'ステージ',src: 'ギフト/ステージ/クラッカー(大)_200pt.png'  },
    {name: 'バラ(大)', icon: '', category: 'ステージ',src: 'ギフト/ステージ/バラ(大)_200pt.png'  },
    {name: '拍手(大)', icon: '', category: 'ステージ',src: 'ギフト/ステージ/拍手(大)_200pt.png'  },      
    {name: 'よーい', icon: '', category: 'ステージ',src: 'ギフト/ステージ/よーい_200pt.png'  },
    {name: 'サーチライト', icon: '', category: 'ステージ',src: 'ギフト/ステージ/サーチライト_200pt.png'  },
    {name: 'もういっかい(大)', icon: '', category: 'ステージ',src: 'ギフト/ステージ/もういっかい(大)_500pt.png'  }, 
    {name: '花束', icon: '', category: 'ステージ',src: 'ギフト/ステージ/花束_500pt.png'  },
    {name: 'スポットライト', icon: '', category: 'ステージ',src: 'ギフト/ステージ/スポットライト_500pt.png'  },
    {name: 'V.I.P', icon: '', category: 'ステージ',src: 'ギフト/ステージ/VIP_500pt.png'  },
    {name: 'くす玉', icon: '', category: 'ステージ',src: 'ギフト/ステージ/くす玉_1,000pt.png'  },
    {name: 'ライト&フォグ', icon: '', category: 'ステージ',src: 'ギフト/ステージ/ライト&フォグ_1,000pt.png'  },   
    {name: 'ライブステージ', icon: '', category: 'ステージ',src: 'ギフト/ステージ/ライブステージ_1,000pt.png'  },
    {name: '花火', icon: '', category: 'ステージ',src: 'ギフト/ステージ/花火_10,000pt.png'  },

    // LOVEカテゴリ
    { name: '好物', category: 'LOVE', src: 'ギフト/LOVE/好物_5pt.png' },
    { name: 'ハート', category: 'LOVE', src: 'ギフト/LOVE/ハート_5pt.png' },
    { name: 'かわいい', icon: '', category: 'LOVE', src: 'ギフト/LOVE/かわいい_5pt.png' },
    { name: '照れ', category: 'LOVE', icon: '', src: 'ギフト/LOVE/照れ_5pt.png' },
    { name: 'キャーッ！', category: 'LOVE', src: 'ギフト/LOVE/キャーッ！_5pt.png' },
    { name: 'あざとい', category: 'LOVE', src: 'ギフト/LOVE/あざとい_5pt.png' },
    { name: 'かわぼ', category: 'LOVE', src: 'ギフト/LOVE/かわぼ_5pt.png' },
    { name: '呼んだ？', category: 'LOVE', src: 'ギフト/LOVE/呼んだ？_5pt.png' },
    { name: 'ハート(大)', category: 'LOVE', src: 'ギフト/LOVE/ハート(大)_200pt.png' },
    { name: 'すっこていい？', category: 'LOVE', src: 'ギフト/LOVE/すっこていい？_500pt.png' },
    { name: '嫁に来ないか・・・？', category: 'LOVE', src: 'ギフト/LOVE/嫁に来ないか・・・？_500pt.png' }, 
    { name: 'ズキューン', category: 'LOVE', src: 'ギフト/LOVE/ズキューン_500pt.png' },
    { name: '唐突な愛', category: 'LOVE', src: 'ギフト/LOVE/唐突な愛_500pt.png' },
    { name: 'ウィンクタイム', category: 'LOVE', src: 'ギフト/LOVE/ウィンクタイム_500pt.png' },
    { name: 'すこ', category: 'LOVE', src: 'ギフト/LOVE/すこ_1,000pt.png' },    
    { name: 'かわいい！', category: 'LOVE', src: 'ギフト/LOVE/かわいい！_3,000pt.png' },
    { name: '尊い', category: 'LOVE', src: 'ギフト/LOVE/尊い_5,000pt.png' },
    { name: 'なでなで', category: 'LOVE', src: 'ギフト/LOVE/なでなで_7,000pt.png' },
    { name: 'だいすき', category: 'LOVE', src: 'ギフト/LOVE/だいすき_10,000pt.png' },
    { name: 'あふれる想い', category: 'LOVE', src: 'ギフト/LOVE/あふれる想い_30,000pt.png' },
];

// --- DOM操作 ---
document.addEventListener('DOMContentLoaded', () => {
    const tabContainer = document.getElementById('tabContainer');
    categories.forEach((cat, idx) => {
        const btn = document.createElement('button');
        btn.className = 'tab-btn' + (idx === 0 ? ' active' : '');
        btn.textContent = cat;
        btn.onclick = () => selectTab(cat, btn);
        tabContainer.appendChild(btn);
    });
    showGifts(categories[0]);
});

function selectTab(category, btn) {
    document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    showGifts(category);
}

function showGifts(category) {
    const giftList = document.getElementById('giftList');
    giftList.innerHTML = '';
    const filtered = gifts.filter(g => g.category === category);
    if (filtered.length === 0) {
        giftList.innerHTML = '<div style="text-align:center; color:#aaa;">このカテゴリのギフトはありません。</div>';
        return;
    }
    filtered.forEach(gift => {
        const item = document.createElement('div');
        item.className = 'gift-item';
        item.innerHTML = `
            <div class="gift-icon">
                <img src="${gift.src}" alt="${gift.name}" class="gift-img" style="width:40px;height:40px;">
            </div>
            <div class="gift-name">${gift.name}</div>
        `;
        giftList.appendChild(item);
    });
}

// 初期表示
showGifts(categories[0]);


